import {
  Box,
  Flex,
  Text,
  Button,
  Input,
  Table,
  TableContainer,
  Tr,
  Th,
  Td,
  Thead,
  Tbody,
} from '@chakra-ui/react';
import React from 'react';

import BackdropExample from '../componentes/modal';

function ListaProductos() {
  const producto = [
    {
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20000000',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
    {
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },{
      codigo: '20',
      descripcion: 'nada por ahora',
      precio: '2',
      existencia: '3',
      iva: '0.2',
    },
  ];

  return producto.map((ele, id) => {
    {console.log(producto.length)}
    return (
      <Tr key={id}>
        <Td>inches</Td>
        <Td whiteSpace="normal" maxWidth="300px">
          ssssssssssssssssss
        </Td>
        <Td isNumeric>{ele.codigo}</Td>
        <Td isNumeric>{ele.iva}</Td>
        <Td>
          <Flex gap={3} justify={'right'}>
            {/* <BackdropExample prod = {ele}></BackdropExample> */}
            sssssssssssssssssssssssssssssssssssssssssssssss
          </Flex>
        </Td>
      </Tr>
    );
    {
      console.log(ele);
    }
  });
}
export function Productos() {
  return (
    <>
      <Box h={'100%'}>
        <Box
          columns={1}
          spacingx="40px"
          spacingy="5px"
          rounded="md"
          p={'7px'}
          h={'17%'}
          boxShadow="outline"
          marginBottom={3}
        >
          <Box>
            <Text paddingBottom={2} textAlign={'initial'} fontSize="md">
              Registrar Productos
            </Text>
          </Box>

          <Flex gap="10">
            <Box w={'9%'}>
              <Text fontSize="sm" textAlign={'initial'}>
                Codigo
              </Text>
              <Input size="xs"></Input>
            </Box>

            <Box w={'40%'}>
              <Text fontSize="sm" textAlign={'initial'}>
                Descripcion
              </Text>
              <Input size="xs"></Input>
            </Box>

            <Box w={'8%'}>
              <Text fontSize="sm" textAlign={'initial'}>
                Precio
              </Text>
              <Input size="xs"></Input>
            </Box>

            <Box w={'9%'}>
              <Text fontSize="sm" textAlign={'initial'}>
                Existencias
              </Text>
              <Input size="xs"></Input>
            </Box>

            <Box w={'8%'}>
              <Text fontSize="sm" textAlign={'initial'}>
                P. Iva
              </Text>
              <Input size="xs"></Input>
            </Box>

            <Box mt="auto">
              <Button size={'sm'}>guardar</Button>
            </Box>
          </Flex>
        </Box>

        <Box h={'80%'}>
          <Box
            pt={3}
            h={'10%'}
            rounded="md"
            boxShadow="outline"
            marginBlock={3}
          >
            <Flex justify={'right'} gap={'3'} align={'center'} paddingEnd={2}>
              <Input size={'xs'} w={'40%'}></Input>
              <Button size={'xs'}>Buscar</Button>
            </Flex>
          </Box>

          <Box overflowY="auto" h={'90%'} paddingEnd={1}>
            <TableContainer>
              <Table variant="striped" colorScheme="teal" size={'sm'}>
                <Thead>
                  <Tr>
                    <Th>Codigo</Th>
                    <Th>Descripcion</Th>
                    <Th isNumeric> Precio</Th>
                    <Th isNumeric> Existencias</Th>
                    <Th isNumeric> Precio</Th>
                  </Tr>
                </Thead>
                <Tbody>
                  <ListaProductos ></ListaProductos>
                </Tbody>
              </Table>
            </TableContainer>
          </Box>
        </Box>
      </Box>
    </>
  );
}
